# Generated by Django 4.0.6 on 2023-07-29 22:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productpacks', '0003_initial'),
        ('discount', '0002_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='productdiscount',
            unique_together={('product_pack', 'discount_code')},
        ),
    ]
