# Generated by Django 4.0.6 on 2022-10-22 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0006_alter_extrafieldvalue_field_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=255, unique=True)),
                ('extra_field_values', models.ManyToManyField(related_name='paks', to='products.extrafieldvalue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paks', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
