# Generated by Django 4.0.6 on 2023-07-19 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('extra_fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('extra_field_values', models.ManyToManyField(blank=True, null=True, related_name='paks', to='extra_fields.extrafieldvalue')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paks', to='products.product')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
