# Generated by Django 4.0.6 on 2023-07-23 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('extra_fields', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('stock', models.IntegerField(default=0)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('sku', models.CharField(blank=True, max_length=255, unique=True)),
                ('extra_field_values', models.ManyToManyField(blank=True, related_name='paks', to='extra_fields.extrafieldvalue')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
