# Generated by Django 4.0.6 on 2022-10-30 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_extrafieldvalue_field_name'),
        ('productpacks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpack',
            name='extra_field_values',
            field=models.ManyToManyField(blank=True, null=True, related_name='paks', to='products.extrafieldvalue'),
        ),
    ]
