# Generated by Django 4.0.6 on 2023-07-23 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_shopstaf_shop_alter_shopstaf_user'),
        ('productpacks', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpack',
            name='shop',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='packs', to='shops.shop'),
        ),
    ]
