# Generated by Django 4.0.6 on 2022-10-31 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productpacks', '0002_alter_productpack_extra_field_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpack',
            name='sku',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
