# Generated by Django 4.0.6 on 2022-12-21 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productpacks', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpack',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
    ]
