# Generated by Django 4.0.6 on 2022-11-05 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_fields', '0001_initial'),
        ('productpacks', '0003_alter_productpack_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpack',
            name='extra_field_values',
            field=models.ManyToManyField(blank=True, null=True, related_name='paks', to='extra_fields.extrafieldvalue'),
        ),
    ]
