# Generated by Django 4.0.6 on 2022-11-14 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_fields', '0002_extrafieldname_sku'),
        ('productpacks', '0004_alter_productpack_extra_field_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpack',
            name='extra_field_values',
            field=models.ManyToManyField(blank=True, related_name='paks', to='extra_fields.extrafieldvalue'),
        ),
    ]
