# Generated by Django 4.0.6 on 2022-11-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_options_alter_user_national_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('cs', 'customer'), ('sl', 'seller')], default='cs', max_length=2),
        ),
    ]
