# Generated by Django 4.0.6 on 2022-11-06 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='sku',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
