# Generated by Django 4.0.6 on 2022-10-17 07:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_extrafieldvalue_field_name'),
        ('carts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='sku',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.CreateModel(
            name='Pack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('sku', models.CharField(max_length=255, null=True, unique=True)),
                ('extra_field_names', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paks', to='products.extrafieldname')),
                ('extra_field_values', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='paks', to='products.extrafieldvalue')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paks', to='products.product')),
            ],
            options={
                'unique_together': {('extra_field_names', 'extra_field_values')},
            },
        ),
        migrations.AddField(
            model_name='cart',
            name='packs',
            field=models.ManyToManyField(related_name='carts', to='carts.pack'),
        ),
    ]
