# Generated by Django 4.0.6 on 2022-10-22 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0002_cart_sku_pack_cart_packs'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pack',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='pack',
            name='extra_field_names',
        ),
        migrations.RemoveField(
            model_name='pack',
            name='extra_field_values',
        ),
        migrations.RemoveField(
            model_name='pack',
            name='product',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Pack',
        ),
    ]
