# Generated by Django 4.0.6 on 2022-12-22 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0004_remove_cartitem_id_remove_cartitem_new_price_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cart',
            old_name='total_price',
            new_name='cart_total_price',
        ),
    ]
