# Generated by Django 4.0.6 on 2022-11-19 07:33

import carts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0005_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1, validators=[carts.validators.validate_none_zero]),
        ),
    ]
