# Generated by Django 4.0.6 on 2023-07-23 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('productpacks', '0001_initial'),
        ('blacklists', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscountCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=30)),
                ('available_untill', models.DateTimeField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProductDiscount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('new_price', models.DecimalField(decimal_places=2, max_digits=14)),
                ('percent', models.PositiveIntegerField(default=0)),
                ('black_list', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='codes', to='blacklists.blacklist')),
                ('discount_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_discounts', to='discount.discountcode')),
                ('product_pack', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_discounts', to='productpacks.productpack')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
