# Generated by Django 4.0.6 on 2023-07-27 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productdiscount',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
