# Generated by Django 4.0.6 on 2023-07-27 11:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('discount', '0003_productdiscount_sku'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productdiscount',
            name='black_list',
        ),
    ]
