# Generated by Django 4.0.6 on 2022-11-13 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extra_fields', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='extrafieldname',
            name='sku',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
