# Generated by Django 4.0.6 on 2023-07-27 11:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('blacklists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blacklist',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='blacklist',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
