# Generated by Django 4.0.6 on 2023-07-27 12:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        ('productpacks', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpack',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='paks', to='products.product'),
        ),
    ]
