# Generated by Django 4.0.6 on 2023-07-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('shops', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ManyToManyField(related_name='products', to='shops.shop'),
        ),
    ]
