# Generated by Django 4.0.6 on 2022-11-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='sku',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='shopaddress',
            name='sku',
            field=models.CharField(blank=True, max_length=255, unique=True),
        ),
    ]
