# Generated by Django 4.0.6 on 2022-11-13 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0002_shop_sku_shopaddress_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopaddress',
            name='address',
            field=models.CharField(max_length=500, unique=True),
        ),
        migrations.AlterField(
            model_name='shopaddress',
            name='postal_code',
            field=models.PositiveBigIntegerField(blank=True, null=True, unique=True),
        ),
    ]
