# Generated by Django 4.0.6 on 2023-07-23 21:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('shops', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopstaf',
            name='shop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopstafs', to='shops.shop'),
        ),
        migrations.AlterField(
            model_name='shopstaf',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shopstafs', to=settings.AUTH_USER_MODEL),
        ),
    ]
