# Generated by Django 4.0.6 on 2023-07-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0003_alter_shopaddress_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='province',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shopaddress',
            name='address',
            field=models.CharField(max_length=500, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='shopaddress',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
