# Generated by Django 4.0.6 on 2022-11-19 07:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('mode', models.CharField(choices=[('of', 'office'), ('hm', 'home'), ('fv', 'favorite'), ('nt', '------')], default='nt', max_length=2)),
                ('name', models.CharField(max_length=64)),
                ('address', models.CharField(max_length=255)),
                ('post_code', models.IntegerField(unique=True, verbose_name='postal code')),
                ('sku', models.CharField(blank=True, max_length=255, unique=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
