# Generated by Django 4.0.6 on 2022-11-20 04:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carts', '0006_alter_cartitem_quantity'),
        ('address', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('payment_method', models.CharField(choices=[('cd', 'cash on delivery'), ('nb', 'net banking'), ('cp', 'card payment'), ('wl', 'wallet')], default='cd', max_length=2, verbose_name='payment method')),
                ('status', models.CharField(choices=[('pn', 'order pending'), ('oa', 'order approved'), ('sp', 'order shipped'), ('od', 'order delivered'), ('oc', 'order cancelled'), ('or', 'order returned')], default='pn', max_length=2)),
                ('sku', models.CharField(blank=True, max_length=255, unique=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='address.address')),
                ('order_cart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cart', to='carts.cart')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
