# Generated by Django 4.0.6 on 2022-11-20 05:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('carts', '0006_alter_cartitem_quantity'),
        ('orders', '0002_orderadmin_remove_order_status_order_order_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='order_admin',
        ),
        migrations.AddField(
            model_name='orderadmin',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='status', to='orders.order'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_cart',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='order', to='carts.cart'),
        ),
    ]
