# Generated by Django 4.0.6 on 2022-11-20 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_remove_order_order_admin_orderadmin_order_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderAdmin',
            new_name='OrderStatus',
        ),
    ]
