# Generated by Django 4.0.6 on 2023-07-19 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0004_alter_shop_name_alter_shop_province_alter_shop_sku_and_more'),
        ('brands', '0003_alter_brand_name'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extrafields',
            name='product',
        ),
        migrations.RemoveField(
            model_name='shop',
            name='address',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='brands.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
        migrations.RemoveField(
            model_name='product',
            name='shop',
        ),
        migrations.AddField(
            model_name='product',
            name='shop',
            field=models.ManyToManyField(related_name='products', to='shops.shop'),
        ),
        migrations.AlterField(
            model_name='product',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='ExtraFields',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
        migrations.DeleteModel(
            name='ShopAddress',
        ),
    ]
