# Generated by Django 4.0.6 on 2022-10-03 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('likes', '0001_initial'),
        ('products', '0002_extrafieldname_extrafieldvalue_delete_extrafields'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='likes',
            field=models.ManyToManyField(to='likes.like'),
        ),
    ]
