# Generated by Django 4.0.6 on 2022-10-15 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_product_likes'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='extrafieldvalue',
            unique_together={('field_name', 'value')},
        ),
    ]
