# Generated by Django 4.0.6 on 2022-10-15 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_extrafieldvalue_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafieldvalue',
            name='field_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='products.extrafieldname'),
        ),
    ]
