# Generated by Django 4.0.6 on 2022-10-31 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_extrafieldvalue_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extrafieldvalue',
            name='sku',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
