# Generated by Django 4.0.6 on 2022-11-04 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_extrafieldvalue_sku'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='extrafieldvalue',
            unique_together={('product', 'field_name', 'value')},
        ),
    ]
