# Generated by Django 4.0.6 on 2022-11-06 04:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shops', '0001_initial'),
        ('brands', '0001_initial'),
        ('products', '0011_remove_product_shop_product_shop'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shop',
            name='address',
        ),
        migrations.AlterField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='brands.brand'),
        ),
        migrations.AlterField(
            model_name='product',
            name='shop',
            field=models.ManyToManyField(related_name='products', to='shops.shop'),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
        migrations.DeleteModel(
            name='Shop',
        ),
        migrations.DeleteModel(
            name='ShopAddress',
        ),
    ]
